name: Nix Build

on:
  push:
    branches: [main]
    paths:
      - "flake.nix"
      - "flake.lock"
  pull_request:
    branches: [main]
    paths:
      - "flake.nix"
      - "flake.lock"

jobs:
  meta-package:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Build meta-package
        run: nix build -L
